### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by indexzero** [os-climate/OS-Climate-Community-Hub#100]
👋 hi friends – former Node.js Foundation & OpenJS Foundation Board Member here. Congrats on the launch! Excited to play around and see how OS-C works under the covers.

Couldn't find the list of all buckets so I just put `*` to request ... well ... everything 😅 because why not? 

Requesting credentials for github user: `indexzero`

Requesting credentials for the bucket: *

Email address to send a credential download link: charlie.robbins@gmail.com

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
Hi @indexzero - sorry for the delayed response.  I just invited you to our github project.  Re: access to buckets, are you interested in Physical Risk & Resilience, Sector Alignment (emissions tracking), and/or Transition Analysis?  We have several workstreams including a few for data mesh infrastructure.  feel free to dm me at hackenhusen@os-climate.org and i can set up time to explain each to see which may be of interest.

**Comment by HeatherAck** [comment]
closing - create new issue if access needed
