### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by SustainableInvest-Scor** [os-climate/OS-Climate-Community-Hub#101]
Requesting onboarding for github user: SustainableInvest-Scor
Request access to github team: odh-env-users, and some other teams.
The main goal is to access data on companies to be able to use the ITR tool for OS-Climate and SBTi.
View teams here: https://github.com/orgs/os-climate/teams
Onboarding resources:
•	[Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
•	[credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)
Onboarding checklist:
•	  new user invited to os-climate github org
•	  user invited to requested teams

I work for SCOR (and this is the offical account of our teams). We would like to test out the tools to gain more understanding for OS-Climate and SBTi.

**Comment by HeatherAck** [comment]
apologies for the delay - I was on vacation.  If you have any questions or run into access issues, please let me know hackenhusen@os-climate.org
