### ISSUE TITLE
Request credentials for an Red Hat OpenShift container platform

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/OS-Climate-Community-Hub#102]
Requesting credentials for github user: LeiDengIDS

Requesting credentials for the Red Hat OpenShift container platform

Email address to send a credential download link: lei.deng@investmentdataservices.com

**Comment by redmikhail** [comment]
Completed with https://github.com/os-climate/ops-argocd/commit/3a9324ffff61ec7666c16d1f3c34146e06eaf369
