### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by yaramohajerani** [os-climate/OS-Climate-Community-Hub#103]
Requesting credentials for github user: **yaramohajerani**

Requesting credentials for the bucket: **osc physical landing** and **Data Loading bucket on Hive / Iceberg**

Email address to send a credential download link: Yara.Mohajerani@ca.ey.com

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by ryanaslett** [comment]
You should be able to access the osc physical landing bucket keys by logging in with your github account here:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys
