### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by yaramohajerani** [os-climate/OS-Climate-Community-Hub#104]
Requesting onboarding for github user: **yaramohajerani**

Request access to github team: physical risk, transition analysis, data commons

View teams here: https://github.com/orgs/os-climate/teams

**I'm requesting to join the os-c github org and get access to Trino. Currently githubidp authentication on both Open MetaData and Trino JWS token retrieval fails. Please assist with accessing Trino data as part of a member organization.** 

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Hi @yaramohajerani - sorry for the delay, I just returned from vacation.  You should have received an invite.  I recommend this as a good resource for an overview for the subprojects that are part of os-climate:  https://github.com/os-climate/OS-Climate-Community-Hub#overview-of-os-cs-projectsworkstreams.  Please feel free to reach out via email:  hackenhusen@os-climate.org if you'd like to meet and go over some on-boarding materials.

**Comment by yaramohajerani** [comment]
Thank you very much @HeatherAck. I have gone over the work streams and attempted accessing trino but there may still be some credential issues. It would be great to have an on-boarding meeting. I will follow through via email.
