### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by moorezhao** [os-climate/OS-Climate-Community-Hub#106]
Requesting onboarding for github user: <[moorezhao](https://github.com/moorezhao)>

Request access to github team: <physical risk, transition analysis, data commons>

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Hi @moorezhao! Welcome to OS-Climate.  Please let me know if you need any help/support with on-boarding (hackenhusen@os-climate.org)
