### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by moorezhao** [os-climate/OS-Climate-Community-Hub#107]
Requesting credentials for github user: moorezhao

Requesting credentials for the bucket: osc physical landing and Data Loading bucket on Hive / Iceberg

Email address to send a credential download link: puyuan.zhao@ca.ey.com

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by moorezhao** [comment]
Hi @HeatherAck, @ryanaslett and @redmikhail, I am a EY employee working with Yara. Could you please approve access to me? Thank you!

**Comment by HeatherAck** [comment]
@ryanaslett @rynofinn and @redmikhail - I approve access.  Please grant.

**Comment by ryanaslett** [comment]
The keys are stored in openshift, you can login using your github account and should be able to see them here at this URL:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys
