### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by mayedaq** [os-climate/OS-Climate-Community-Hub#109]
Requesting credentials for github user: <github-user-name>

Requesting credentials for the bucket: <bucket-name>

Email address to send a credential download link: <email-address>

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by mayedaq** [comment]
Requesting credentials for github user: mayedaq

Requesting credentials for the bucket: osc physical landing and Data Loading bucket on Hive / Iceberg

Email address to send a credential download link: mayeda.quadir@ca.ey.com

**Comment by HeatherAck** [comment]
@ryanaslett @rynofinn @redmikhail - I approve.  Please grant access.

**Comment by ryanaslett** [comment]
You have been added to the github organziation 'odh-env-users'. Once you accept the invite, you will be able to access the keys.

The keys are stored in openshift, you can login using your github account and should be able to see them here at this URL:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys
