### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by judith-feredj** [os-climate/OS-Climate-Community-Hub#111]
Requesting credentials for github user: feredj-judith

Requesting credentials for the bucket: https://github.com/os-climate/physrisk

Email address to send a credential download link: Judith.feredj@yahoo.fr

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
@ryanaslett please grant Judith access.  She is from BCG.  @judith-feredj I invited you to os-climate's github and Physical Risk Project Team.  Please let me know if you would like to meet for an on-boarding session.

Thanks,
Heather
