### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by EglantineGiraud** [os-climate/OS-Climate-Community-Hub#112]
Requesting credentials for github user: EglantineGiraud

Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Email address to send a credential download link: eglantine.giraud@gmail.com

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
@ryanaslett - i approve this user's access.  please provide credentials

**Comment by EglantineGiraud** [comment]
Many thanks, I managed to see my keys.
