### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by annbaz123** [os-climate/OS-Climate-Community-Hub#114]
Requesting credentials for github user: annbaz123

Requesting credentials for the bucket: os-climate bucket

Email address to send a credential download link: anntruong@live.com.au

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
Hi @annbaz123 

The keys are stored in openshift, you can login using your github account and should be able to see them here at this URL:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys

@eharrison24 @strawberry-baked-alaska
