### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by annbaz123** [os-climate/OS-Climate-Community-Hub#115]
Requesting onboarding for github user: annbaz123

Request access to github team:  OSC Data Commons

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Hi Ann - I invited you to the our git hub and teams

**Comment by strawberry-baked-alaska** [comment]
Accepted invite.
