### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by jeffchenchengyi-bcg** [os-climate/OS-Climate-Community-Hub#118]
Requesting credentials for github user: jeffchenchengyi-bcg

Requesting credentials for the bucket: os-climate

Email address to send a credential download link: chen.jeff@bcg.com

Request checklist:
- [✔] User can establish connection with the bucket
- [✔] User can read files from the bucket
- [✘] User can write files to the bucket

**Comment by strawberry-baked-alaska** [comment]
Sent invitation to join. Please reach out if you need anything further.
