### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by jeffchenchengyi-bcg** [os-climate/OS-Climate-Community-Hub#119]
Requesting onboarding for github user: jeffchenchengyi-bcg

Request access to github team: <physical risk, transition analysis, data commons>

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [ ] new user invited to os-climate github org
- [ ] user invited to requested teams

Hi @strawberry-baked-alaska! Thanks for sending me an invitation to join! Could I also get access to OSC Data Commons? Thanks!

**Comment by strawberry-baked-alaska** [comment]
@ryanaslett @rynofinn @redmikhail - I approve. Please grant access.

**Comment by ryanaslett** [comment]
I have added @jeffchenchengyi-bcg  to the physical risk, transition analysis, and data commons teams. 

The keys to the physical risk landing bucket should be accessable at this url:
https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys
 
 Let me know if you have more questions!

**Comment by eharrison24** [comment]
Thanks Ryan.

Evan
