### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by dcosteroarfima** [os-climate/OS-Climate-Community-Hub#120]
Requesting credentials for github user: dcosteroarfima

Requesting credentials for the bucket: physrisk-hazard-indicators and physrisk-hazard-indicators-dev01

Email address to send a credential download link: dcostero@arfimaconsulting.com

Request checklist:
- [X] User can establish connection with the bucket
- [X] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by eharrison24** [comment]
Hello,

Thank you for your request. This has been approved. @ryanaslett  please grant access to this user.

**Comment by eharrison24** [comment]
@ryanaslett Can you please invite him to the ODH team as well as the physical risk team.

**Comment by eharrison24** [comment]
Hi @ryanaslett do you have any updates for this ticket?

Evan

**Comment by ryanaslett** [comment]
You have been added to the github organziation 'odh-env-users'. Once you accept the invite, you will be able to access the keys.

The keys are stored in openshift, you can login using your github account and should be able to see them here at this URL:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys
