### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by pushkarsharma25** [os-climate/OS-Climate-Community-Hub#121]
Requesting credentials for github user: pushkarsharma25

Requesting credentials for the bucket: physrisk-hazard-indicators

Email address to send a credential download link: pushkarsharma2014@gmail.com

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by strawberry-baked-alaska** [comment]
@eharrison24 - please take a look, thanks!

**Comment by eharrison24** [comment]
Hi Pushkar,

Thanks for you interest in OS-C climate! I will start the process of providing the proper permissions! @ryanaslett can you please take a look at this?

**Comment by PS-PR-SE** [comment]
Thanks! Evan Harrison.

**Comment by pushkarsharma25** [comment]
Thanks! Evan Harrison.

**Comment by eharrison24** [comment]
Hi @ryanaslett Do you have any updates for this ticket?

Evan

**Comment by ryanaslett** [comment]
You have been added to the github organziation 'odh-env-users'. Once you accept the invite, you will be able to access the keys.

The keys are stored in openshift, you can login using your github account and should be able to see them here at this URL:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys

**Comment by pushkarsharma25** [comment]
Thanks! @ryanaslett @eharrison24.
