### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by rainergo** [os-climate/OS-Climate-Community-Hub#126]
Requesting credentials for github user: rainergo

Requesting credentials for the bucket: os-climate

Email address to send a credential download link: rainer.gogel@web.de

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket

**Comment by eharrison24** [comment]
Hello, 

Thank for you your interest in OS-Climate. @ryanaslett can you please add this user to the ODH please.

Evan

**Comment by ryanaslett** [comment]
You have been added to the github organziation 'odh-env-users'. Once you accept the invite, you will be able to access the keys.

The keys are stored in openshift, you can login using your github account and should be able to see them here at this URL:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys
