### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by jfmiller83** [os-climate/OS-Climate-Community-Hub#128]
Requesting credentials for github user: <jfmiller83>

Requesting credentials for the bucket: <os-climate-public-data>

Email address to send a credential download link: <jfmiller83@gmail.com>

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by eharrison24** [comment]
Hello,

Thank you for your interest in OS-Climate! Can you please let me know know what interests you about OS-Climate and what repos you would like to be a part of?

Best,
Evan

**Comment by HeatherAck** [comment]
Hi @jfmiller83 - I sent you an invite to join our github.  Once you accept the invite you should be able to gain access.

The keys are stored in openshift, you can login using your github account and should be able to see them here at this URL:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys

@eharrison24 @strawberry-baked-alaska
