### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by Carina-vd-Merwe** [os-climate/OS-Climate-Community-Hub#132]
Requesting credentials for github user: <Carina-vd-Merwe>

Requesting credentials for the bucket: <S3 Bucket>

Email address to send a credential download link: <carina.van-der-merwe@mazars.co.uk>

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
@eharrison24 - pinging on this just in case you missed it

**Comment by eharrison24** [comment]
Hi Carina, sorry for the delay! Are there any specific repositories you would like to be added to?

**Comment by Carina-vd-Merwe** [comment]
Good day,

Thank you for getting back to me. I am not sure about the exact repositories. I want to use the physrisk-lib on my local, and for that, I require access to the hazard indicator data, which requires the setting of environmental variables specifying the S3 Bucket – therefore access to the S3 Bucket is required.

I hope this helps.

Kind regards,
Carina
Quant Analyst – Quantitative Solutions
Mobile: +44 (0)79 7776 1196
***@***.******@***.***>
Visit our Climate Risk page: Climate risk - Mazars<https://www.mazars.co.uk/Home/Industries/Financial-Services/Banking-Capital-Markets/Climate-risk>

***@***.***

**Comment by HeatherAck** [comment]
hi @Carina-vd-Merwe - The keys are stored in openshift, you can login using your github account and should be able to see them here at this URL:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys

@eharrison24 @strawberry-baked-alaska

**Comment by eharrison24** [comment]
Hi @HeatherAck and @Carina-vd-Merwe 

I wanted to apologize for the delay, Carina. I didn't see your notification last week that you responded. That's my fault! Please let me know if there is anything else that you need that wasn't covered in our email exchange this morning (12/6).

Heather, I found the link that Ryan Aslett sent that allows users to access the Openshift platfrom credentials. The link was to Carina this morning (12/6).

Best,
Evan
