### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by jiahknee5** [os-climate/OS-Climate-Community-Hub#137]
Requesting credentials for github user: jiahknee5

Requesting credentials for the bucket: <bucket-name>

Email address to send a credential download link: jiahknee5@gmail.com

Request checklist:

- [x ] User can establish connection with the bucket
- [ x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by strawberry-baked-alaska** [comment]
Hello @jiahknee5 

Thank you for your interest in OS-Climate! Can you please let me know know what interests you about OS-Climate and what repos you would like to be a part of?

Regards,
Jenn

**Comment by MightyNerdEric** [comment]
We need the buckets specified in order to complete this request.

**Comment by HeatherAck** [comment]
Hi @jiahknee5 

The keys are stored in openshift, you can login using your github account and should be able to see them here at this URL:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys

@eharrison24 @strawberry-baked-alaska

**Comment by jiahknee5** [comment]
Hi -

Thank you for sending this.   After an attempt in logging in, I get the error:  an autentication error occurred.   Is it because this was over a month ago?

Thanks,
Johnny

**Comment by HeatherAck** [comment]
Hi Johnny,

probably - i resent the invite just now.  please try again

**Comment by ModeSevenIndustrialSolutions** [comment]
Closing due to lack of updates.
