### ISSUE TITLE
observations vs estimations

### ISSUE THREAD

**Issue by OferHarari** [os-climate/OS-Climate-Community-Hub#14]
Hi team
Sapna and I met internally with our ESG team. A KPI-related topic was the need to distinguish and indicate if a KPI is an observation or an estimation. 
-          Observations are harder to find, and less data is available.
-          Estimations might not be accurate and might not be accepted by regulators.
 
Any thoughts?

From Vincent:
Hi Ofer, 

This discussion would certainly deserve opening an issue in our GitHub (under Data Commons).

My quick thoughts more from the platform point of view:
•	Defining which data is estimation (as well as associated information such as date, basis for estimation, etc...) is metadata we will want to manage.
•	Ability to have metadata tagging for estimations vs. observations is something that we can definitely plan to use as a basis for data access / security but also could be used in quality gates / checks in data pipelines.
•	It would be wonderful to have an example of a data domains where different sources can provide estimations / observations of the same metrics, so we could conceptually discuss the required handling in one of our storming sessions.
Thanks for raising this item to attention.

**Comment by ModeSevenIndustrialSolutions** [comment]
This never got assigned to anybody and the silence in this issue is deafening. Can we close it?
