### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by jainur** [os-climate/OS-Climate-Community-Hub#142]
Requesting credentials for github user: jainur@gmail.com

Requesting credentials for the bucket: OSC Data Commons and Physical Risk & Resilience

Email address to send a credential download link: jainur@gmail.com

I'm requesting to join the os-c github org and get access to Trino. Currently githubidp authentication on both Open MetaData and Trino JWS token retrieval fails. Please assist with accessing Trino data as part of a member organization.

Request checklist:

- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by strawberry-baked-alaska** [comment]
I sent you an invite to join our github. Once you accept the invite you should be able to gain access.

The keys are stored in openshift, you can login using your github account and should be able to see them here at this URL:

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys

**Comment by jainur** [comment]
Thank you. I have accepted the invitation and can login to CL 1 and 2. 

However, for some reason, access to trino (using notebooks e.,g., https://github.com/os-climate/data-platform-demo/blob/master/notebooks/trino-pandas-demo.ipynb) does not work. How to gain / request this access?

**Comment by strawberry-baked-alaska** [comment]
@redmikhail or @ModeSevenIndustrialSolutions - can you take a look please?

**Comment by jainur** [comment]
Thanks. I still did not have any luck with Trino access. I will ask this question on Slack.

**Comment by ModeSevenIndustrialSolutions** [comment]
I have asked a couple of my technical contacts how we go about granting access to Trino. I believe this resides on the OS-Climate RedHat Openshift cluster.

Do you already have a RedHat account?
https://redhat.com/
https://sso.redhat.com/auth/realms/redhat-external/account/

I think this is a prerequisite, so perhaps register for one now while you are waiting for me to get back to you?

**Comment by jainur** [comment]
thank you @ModeSevenIndustrialSolutions . I will try and come back.

**Comment by jainur** [comment]
Dear @ModeSevenIndustrialSolutions - 

Unfortunately, I could not get past the wall. I am doing something stupid, not sure what. 

I tried the following:

- Registered at redhat (based on the suggestion above). My user name is: jainur@gmail.com
- I have the following in my .env file:
# user trino credentials
# Get your JWT token from:
# new: https://das-odh-trino.apps.odh-cl2.apps.os-climate.org
TRINO_USER=jainur@gmail.com

TRINO_PASSWD= <<Token generated using this [link](https://das-odh-trino.apps.odh-cl2.apps.os-climate.org/)>>
TRINO_HOST=das-odh-trino.apps.odh-cl2.apps.os-climate.org
TRINO_PORT=443

And when I execute the notebook, I get the following error:

![image](https://github.com/user-attachments/assets/5ebcc258-51ec-4064-ab5a-a9e4adff0315)


Not sure what and where things are going wrong.

**Comment by ModeSevenIndustrialSolutions** [comment]
@redmikhail Any chance you can pick this up, take a look?

**Comment by redmikhail** [comment]
@jainur My apologies for delay .  Trino in this case is using JWT authentication with token generated based on your id. DAS application is just a ui to generate token (please note that token expires)
1. Use DAS https://das-odh-trino.apps.odh-cl2.apps.os-climate.org/ to generate token (select Github authentincation)
2. URL for actual trino should be - `https://trino-secure-odh-trino.apps.odh-cl2.apps.os-climate.org` or `trino-secure-odh-trino.apps.odh-cl2.apps.os-climate.org` . (DAS is being used to generate token)
3. Copy generated token and use it with JWT authentication (https://github.com/trinodb/trino-python-client/blob/master/README.md#jwt-authentication) , eg. you just need to provide token
_Note:To verify connection you can use curl : ```
curl -k https://trino-secure-odh-trino.apps.odh-cl2.apps.os-climate.org/v1/statement/ \
--header "Authorization: Bearer <your token generated in step 1>" \
--data "select * from default"```

Please let me know if you have any issues . You can also ping me on Slack

**Comment by ModeSevenIndustrialSolutions** [comment]
No response in three weeks? I assume this ticket can be closed. We can re-open, if necessary.

**Comment by jainur** [comment]
Hi @ModeSevenIndustrialSolutions , the issue is not yet closed. I have reached out to Mikhail on Slack but waiting for his inputs.
