### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by Revanounet** [os-climate/OS-Climate-Community-Hub#145]
Requesting credentials for github user: Revanounet

Requesting credentials for the bucket: OS-Climate S3 buckets, OS-Climate S2 buckets, OS-Climate S1 buckets

Email address to send a credential download link: savinien.jesu@gmail.com

Request checklist:

- [X ] User can establish connection with the bucket
- [ X] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by strawberry-baked-alaska** [comment]
Hello,

Thank you for your interest in OS-Climate! Can you please let me know know what interests you about OS-Climate and what repos you would like to be a part of?

Best,
Jenn

**Comment by ModeSevenIndustrialSolutions** [comment]
@Revanounet Can you answer the question above?
I'm assuming you got access to the bucket through another channel, can you confirm?

**Comment by ModeSevenIndustrialSolutions** [comment]
Closing due to lack of response.
