### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by ParthibanGowthaman** [os-climate/OS-Climate-Community-Hub#146]
Requesting credentials for github user: ParthibanGowthaman

Requesting credentials for the bucket: physrisk-hazard-indicators

Email address to send a credential download link: gowthamparthiban@gmail.com

Request checklist:

- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by strawberry-baked-alaska** [comment]
Thank you for your interest in OS-Climate! Can you please let me know know what interests you about OS-Climate and what repos you would like to be a part of? It looks like you have an interest in Phys Risk, but if you have any additional information to provide, we'd appreciate hearing from you before we open up access. Thanks!

**Comment by ModeSevenIndustrialSolutions** [comment]
@ParthibanGowthaman Can you answer the question above?
I'mn assuming you got access through another channel. Is this request still open?

**Comment by ModeSevenIndustrialSolutions** [comment]
Thanks for confirmation.
