### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by lucaborella89** [os-climate/OS-Climate-Community-Hub#147]
Requesting credentials for github user: lucaborella89

Requesting credentials for the bucket: WRI Aqueduct flood data

Email address to send a credential download link: luca.borella@algoritmica.ai

Request checklist:

- [X] User can establish connection with the bucket
- [X] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by MichaelTiemannOSC** [comment]
I sent an invitation to join our project.

We don't have WRI Aqueduct flood data.  It is best to get that directly from the source: https://www.wri.org/data/aqueduct-global-maps-40-data
