### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by ArianeDlns** [os-climate/OS-Climate-Community-Hub#148]
Requesting credentials for github user: ArianeDlns

Requesting credentials for the bucket: https://github.com/os-climate/physrisk

Email address to send a credential download link: arianedlns@gmail.com

Request checklist:

- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by ArianeDlns** [comment]
#111 working with @judith-feredj - would it be possible to have a set of credentials, 

Best, 
Ariane

**Comment by ModeSevenIndustrialSolutions** [comment]
I believe the correct S3 bucket is actually:

os-climate-physrisk-hazard-indicators

Sent the following email today:

From: Matt Watkins <mwatkins@linuxfoundation.org>
Subject: Request: OS-Climate-Community-Hub/issues/148
Date: 27 August 2024 at 15:44:44 BST
To: arianedlns@gmail.com

Hi,

We received your access request here:

https://github.com/os-climate/OS-Climate-Community-Hub/issues/148

Find attached a CSV file containing the requested credentials with read-only permissions.

Thanks,

- Matt Watkins

The Linux Foundation
Release Engineering Team

https://www.linuxfoundation.org/
[mwatkins@linuxfoundation.org](mailto:mwatkins@linuxfoundation.org)
