### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by borisyy13** [os-climate/OS-Climate-Community-Hub#149]
Requesting credentials for github user: borisyy13

Requesting credentials for the bucket: physrisk-hazard-indicators

Email address to send a credential download link: boris.yendrzheyevskiy@riskcare.com

Request checklist:

- [x ] User can establish connection with the bucket
- [ x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by borisyy13** [comment]
do not need writing

**Comment by ModeSevenIndustrialSolutions** [comment]
@borisyy13 Can you answer this question?
If you still need this can you reply on the issue?

**Comment by ModeSevenIndustrialSolutions** [comment]
Closing due to lack of response.
