### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by othmanerhaouti-bcg** [os-climate/OS-Climate-Community-Hub#153]
Requesting credentials for github user: othmanerhaouti-bcg

Requesting credentials for the bucket: https://github.com/os-climate/physrisk

Email address to send a credential download link: rhaouti.othmane@bcg.com

Request checklist:

- [X] User can establish connection with the bucket
- [X] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by strawberry-baked-alaska** [comment]
Thank you for your interest in OS-Climate! Can you please let me know know what interests you about OS-Climate and what repos you would like to be a part of? It looks like you have an interest in Phys Risk, but if you have any additional information to provide, we'd appreciate hearing from you before we open up access. Thanks!

**Comment by othmanerhaouti-bcg** [comment]
Thanks for your answer! 
I want to use the OS-Climate data in order to assess the climate physical risk on a set of assets.
To do so, I need to know the level of different vulnerabilities at the assets location for the 2050 horizon.

**Comment by MichaelTiemannOSC** [comment]
Credentials provided via private communications.
