### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by rohit-jain-alptech** [os-climate/OS-Climate-Community-Hub#157]
Requesting credentials for github user: [rohit-jain-alptech]

Requesting credentials for the bucket: [OSC_S3_BUCKET_DEV]

Email address to send a credential download link: [rohit.jain@alptech.io]

Request checklist:

- [x] User can establish connection with the bucket
- [x] User can read files from the bucket

**Comment by ModeSevenIndustrialSolutions** [comment]
Hi,

This does not correspond to a valid OS-Climate S3 bucket.

Which project data are you wanting to access?

- Matt

**Comment by ModeSevenIndustrialSolutions** [comment]
Closing due to lack of response.
