### ISSUE TITLE
Request Onboarding to OSC Data Commons and os-climate bucket

### ISSUE THREAD

**Issue by DidierRLopes** [os-climate/OS-Climate-Community-Hub#158]
Requesting onboarding for github user: DidierRLopes

Requesting credentials for the bucket: OSC Data Commons and Physical Risk & Resilience

Email address to send a credential download link: didier.lopes@openbb.finance

I'm with [OpenBB](https://github.com/OpenBB-finance/OpenBB) and my point of contact is Gabriele Columbro / Luca Borella.

**Comment by ModeSevenIndustrialSolutions** [comment]
From: Matt Watkins <mwatkins@linuxfoundation.org>
Subject: OS-Climate: Physical Risk/S3 Bucket Access
Date: 20 August 2024 at 14:37:59 BST
To: didier.lopes@openbb.finance

Hi,

I am responding to your request/issue in the OS-Climate GitHub account here:

https://github.com/os-climate/OS-Climate-Community-Hub/issues/158

Please find attached a read-only credential to the AWS S3 bucket.

Let me know if you have any further questions?

Many thanks,

- Matt Watkins

The Linux Foundation
Release Engineering Team

https://www.linuxfoundation.org/
mwatkins@linuxfoundation.org

[attachment removed]
