### ISSUE TITLE
Code of Conduct link is dead

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/OS-Climate-Community-Hub#159]
The general README.md file references an LF resource that no longer exists: https://lfprojects.org/policies/code-of-conduct/

This might be the new resource that should be referenced: https://docs.linuxfoundation.org/lfx/mentorship/mentor-guide/code-of-conduct (but the fact that it's situated in mentorship makes me wonder).

I'm sure we need to do a complete review/rewrite of this page, but this particular issue should be addressed directly.

**Comment by ModeSevenIndustrialSolutions** [comment]
Looks like the original link is working again.
![Uploading Screenshot 2024-08-27 at 15.05.38.png…]()

**Comment by ModeSevenIndustrialSolutions** [comment]
Looks like the original link is working again.
<img width="1297" alt="Screenshot 2024-08-27 at 15 05 38" src="https://github.com/user-attachments/assets/ac88e29e-3f88-43e7-aad0-4385de42117e">
