### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by nomunzul-b** [os-climate/OS-Climate-Community-Hub#160]
Requesting credentials for github user: [nomunzul-b]

Requesting credentials for the bucket: [os-climate-physrisk-hazard-indicators]

Email address to send a credential download link: [nomunzul@stanford.edu]

Request checklist:

- [Y] User can establish connection with the bucket
- [Y] User can read files from the bucket
- [N] User can write files to the bucket

**Comment by ModeSevenIndustrialSolutions** [comment]
Begin forwarded message:

From: Matt Watkins <mwatkins@linuxfoundation.org>
Subject: Credentials for the bucket: [os-climate-physrisk-hazard-indicators]
Date: 27 August 2024 at 15:36:49 BST
To: nomunzul@stanford.edu

Hi,

We received your access request here:

https://github.com/os-climate/OS-Climate-Community-Hub/issues/160

Find attached a CSV file containing the requested credentials,

Thanks,

- Matt Watkins

The Linux Foundation
Release Engineering Team

https://www.linuxfoundation.org/
mwatkins@linuxfoundation.org
