### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by Florian64** [os-climate/OS-Climate-Community-Hub#164]
Requesting credentials for github user: Florian64

Requesting credentials for the bucket: https://github.com/os-climate/physrisk

Email address to send a credential download link: florian.lalanne@yahoo.fr

Request checklist:

- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

I would like to use the OS-Climate data in order to assess the climate physical risk on a database of assets.
To do so, I need to know the level of different vulnerabilities at the assets location for the 2050 horizon.

**Comment by ModeSevenIndustrialSolutions** [comment]
From: Matt Watkins <mwatkins@linuxfoundation.org>
Subject: Request: OS-Climate-Community-Hub
Date: 6 September 2024 at 09:45:28 BST
To: florian.lalanne@yahoo.fr

Hi,

We received your access request here:

https://github.com/os-climate/OS-Climate-Community-Hub/issues/164

Find attached a CSV file containing the requested credentials with read-only permissions.

Thanks,

- Matt Watkins

The Linux Foundation
Release Engineering Team

https://www.linuxfoundation.org/
[mwatkins@linuxfoundation.org](mailto:mwatkins@linuxfoundation.org)
