### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by codunlaing** [os-climate/OS-Climate-Community-Hub#171]
Requesting onboarding for github user: codunlaing

Request access to github team: [os_c_data_commons](https://github.com/os-climate/os_c_data_commons)

View teams here: <https://github.com/orgs/os-climate/teams>

Onboarding resources:

- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:

- [ ] new user invited to os-climate github org
- [ ] user invited to requested teams

**Comment by wendallkaters** [comment]
Thank you for your interest in OS-Climate! Can you please let me know know what interests you about OS-Climate and what repos you would like to be a part of? It looks like you have an interest in Data Commons, but if you have any additional information to provide, we'd appreciate hearing from you before we open up access. Thanks!

**Comment by ModeSevenIndustrialSolutions** [comment]
@codunlaing Are you able to reply to the query above added to your request? Some basic information about the nature of your interest, what you intend to do with the team/access, and other background would be helpful, thanks.
