### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by aditigautam78** [os-climate/OS-Climate-Community-Hub#175]
Requesting credentials for github user: aditigautam78

Requesting credentials for the bucket:  OS-Climate data

Email address to send a credential download link: adgautam@nvidia.com

Request checklist:

- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by wendallkaters** [comment]
Thank you for your interest in OS-Climate! Can you please let me know know what interests you about OS-Climate and what repos you would like to be a part of? If you have any additional information to provide, we'd appreciate hearing from you before we open up access. Thanks!

**Comment by wendallkaters** [comment]
@MichaelTiemannOSC - are you able to help with this request?

**Comment by MichaelTiemannOSC** [comment]
Glad to have you involved!  We are in the final stage (?) of shifting all the physrisk data from private buckets to data hosted by ASDI.  @ModeSevenIndustrialSolutions may have visibility into when that may happen.  If not as soon as I think, he can give you read-only credentials and ability to list buckets within the physrisk space.  But the ASDI-hosting will make everybody's life much easier.
