### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by helena-intel** [os-climate/OS-Climate-Community-Hub#22]
Requesting credentials for github user: helena-intel

Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by erikerlandson** [comment]
@helena-intel  I have sent you a download link and password (separately) to get physical landing s3 creds.
Let me know if you can verify the checklist above when you get them.
