### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by helena-intel** [os-climate/OS-Climate-Community-Hub#23]
Requesting onboarding for github user: helena-intel

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by erikerlandson** [comment]
@helena-intel  I have sent invite to os-climate, and added you to the AICoE-OSC-Demo team.
I am going to close this, but if you run into any problems feel free to re-open.

**Comment by helena-intel** [comment]
@erikerlandson could you please re-send the invite?

**Comment by HeatherAck** [comment]
hi all - saw that the invite was still in expired status so just resent
