### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by JeremyGohBNP** [os-climate/OS-Climate-Community-Hub#26]
Due to a security incident, I heard that we had to ask for a new access key for OSC S3 bucket. Would it be possible to issue that for me? Thanks! @redmikhail

**Comment by JeremyGohBNP** [comment]
Up! Can you please address this issue because I would like to access the S3 bucket? Thanks

**Comment by erikerlandson** [comment]
you should receive a download link and passwd.  re-open this issue if you run into any problems
