### ISSUE TITLE
Need a DCO onboarding link

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/OS-Climate-Community-Hub#28]
The onboarding materials state:

```
All project contributors are expected to adhere to the Linux Foundation DCO Policy
https://wiki.linuxfoundation.org/dco
```

We need a reference document about how to make this work for our expected developer environments: Jupyter Notebooks running either on OS-Climate nodes or on developers' desktops.  But also developers who use other IDEs and use GitHub Desktop and/or the GitHub CLI.

We also need instructions on how to fix DCO errors, and in particular, resources we can go to when we are not comfortable doing things to GitHub repos that are not part of the normal push/pull process.

**Comment by MichaelTiemannOSC** [comment]
I don't know who did what, but the Pull Request I submitted this morning had a sign-off integrated, even though I did nothing different.  If that's the fix, I'm happy to close!

https://github.com/os-climate/ITR/pull/90

**Comment by cdeliaRH** [comment]
Not sure what happened as I did not do anything @MichaelTiemannOSC

**Comment by HeatherAck** [comment]
@MichaelTiemannOSC - I created the following doc which includes more details on Contributing and in particular, DCO.  Feedback appreciated:  https://github.com/os-climate/OS-Climate-Community-Hub/blob/main/Contributing.md  Also, I believe the LF team just added the new DCO signoff integration into the UI.  See pic below - is this what you saw when you did the pull request?

![image](https://user-images.githubusercontent.com/90428947/167230706-6974708d-6f65-4789-a222-daf0e591631d.png)

**Comment by MightyNerdEric** [comment]
That documentation already contains my main advice:
`git commit --amend --signoff`
In fact, you don't even need to bring up an editor:
`git commit --amend --signoff --no-edit`

@MichaelTiemannOSC Could you detail how you got the bad result on your first try?

**Comment by MichaelTiemannOSC** [comment]
Here's an example of a step-by-step set of instructions for how some Red Hat communities do their GitHub commits, pull-requests etc.  This could be adapted to give an end-to-end example for how things should be done for OS-Climate (including pre-commit checks, argo CI/CD, black, prow, DCO, and everything else that makes life just a little more complicated): https://developers.redhat.com/articles/command-line-heroes-game-pull-request#

**Comment by eoriorda** [comment]
Cryptographic Signrature - 

Need all OSC to follow same process .  
Need to make sure good gatekeeping on each commit but also use case for commits in an emergency.
1. Develop standard procedure for normal commits with notebooks using the video as a guide
2. Add to the process for emergency commits

**Comment by eoriorda** [comment]
Eric Hall is working on improved documentation using Michael link as a start. Helping people create DCO add them to code.  DCO is required on all LF projects. 
Michael T asked is there a way to link a precommit hook to the gitcommit-s . Use the users local config  and it only has to be done once.

**Comment by HeatherAck** [comment]
initial version of docs on 23-Aug; also will look at using githooks, so devs know if DCO is missing upon commit (automating it cannot be done)

**Comment by eoriorda** [comment]
Change : Eric B submitted a  Pull request to review and update documents  .   More feedback needed from Michael T and also look to other experts in this area.

**Comment by eoriorda** [comment]
Michael T happy to close
