### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by mamurak** [os-climate/OS-Climate-Community-Hub#30]
Requesting credentials for github user: mamurak

Requesting credentials for the bucket: a bucket that contains samples for running the os climate demo

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by erikerlandson** [comment]
I have emailed you download link for physical landing bucket credentials
