### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by DaBeIDS** [os-climate/OS-Climate-Community-Hub#32]
Requesting credentials for github user: DaBeIDS

Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Request checklist:
- [x] User can establish connection with the bucket
- [X] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by erikerlandson** [comment]
@DaBeIDS  apologies, I need an email address to send download link

**Comment by DaBeIDS** [comment]
Hi Eric, sorry for the missing info.
david.besslich@investmentdataservices.com

**Comment by erikerlandson** [comment]
@DaBeIDS it's my fault, I've updated the issue template to ask for emails

**Comment by erikerlandson** [comment]
@DaBeIDS  I have sent you a download link and password (separately)

**Comment by DaBeIDS** [comment]
@erikerlandson Thanks, received both and have downloaded it.
