### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by ChristianMeyndt** [os-climate/OS-Climate-Community-Hub#33]
Requesting credentials for github user: ChristianMeyndt

Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by erikerlandson** [comment]
Download link sent
