### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by mriefer** [os-climate/OS-Climate-Community-Hub#34]
Requesting credentials for github user: mriefer
Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Request checklist:
- [X] User can establish connection with the bucket
- [X] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by erikerlandson** [comment]
@mriefer apologies, I need an email to send download link to

**Comment by mriefer** [comment]
@erikerlandson please send the link to riefer.max@gmail.com, thank you.

**Comment by HeatherAck** [comment]
@erikerlandson can this be closed?
