### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by oindrillac** [os-climate/OS-Climate-Community-Hub#35]
Requesting onboarding for github user: @romeokienzler

Request access to github team: [odh-env-users](https://github.com/orgs/os-climate/teams/odh-env-users)
View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Sent invite to org and related teams.  Adding @erikerlandson to send credentials

**Comment by HeatherAck** [comment]
@erikerlandson can this be closed
