### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by SKZHA** [os-climate/OS-Climate-Community-Hub#37]
Requesting credentials for github user: SKZHA

Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Email address to send a credential download link: shikang.zhao@hotmail.com

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

Thanks!

**Comment by erikerlandson** [comment]
Hi @SKZHA, I have sent you a download link and (separately) a download password

**Comment by SKZHA** [comment]
Thanks a lot @erikerlandson . The connection succeeded.
