### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by Jonathan-Belhassen** [os-climate/OS-Climate-Community-Hub#39]
Requesting credentials for github user: Jonathan-Belhassen

Requesting credentials for the bucket:  redhat-osc-physical-landing-647521352890

Email address to send a credential download link: jonathan.belhassen@bnpparibas.com

Request checklist:
- [x ] User can establish connection with the bucket
- [ x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
@erikerlandson can we close this?
