### ISSUE TITLE
Request credentials for an os-climate bucket itr

### ISSUE THREAD

**Issue by ghost** [os-climate/OS-Climate-Community-Hub#43]
Requesting credentials for github user: dunstanm

Requesting credentials for the bucket: itr

Email address to send a credential download link: dunstan.marris@gs.com

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by dunstanm** [comment]
hi,  I meant to apply as dunstanm,   but accidentally used an old sign-in.  I have deleted to avoid further confusion, and will re-raise for clarity
