### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by thierryc01** [os-climate/OS-Climate-Community-Hub#47]
Requesting onboarding for github user: thierryc01

Request access to GitHub teams:   Don't know....  the link below does not work.
I'm today interested in the projects related to OSC Data Commons, Trino database, and NLP stuff. 

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
@thierryc01 just sent you an invite to OS-C's github and related Data Commons and Data Extraction teams
