### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by yoann-diep** [os-climate/OS-Climate-Community-Hub#48]
Requesting onboarding for github user: yoann-diep

Request access to github team: <team-name(s)>

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Welcome @yoann-diep!  I invited you to our github.  This is a great resource in helping you get on-boarded: https://github.com/os-climate/OS-Climate-Community-Hub/blob/main/README.md.  Please let me know if you need any help.
