### ISSUE TITLE
Remove unused repos esg_model_pipeline_notebook and esg_data_pipeline_notebook

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/OS-Climate-Community-Hub#49]
These two repos are placeholders over a year old.  I think they should be culled.

https://github.com/os-climate/esg_model_pipeline_notebook
https://github.com/os-climate/esg_data_pipeline_notebook

**Comment by ModeSevenIndustrialSolutions** [comment]
Due to lack of progress on this topic, I've archived both these repositories in GitHub (it's a reversible operation)
