### ISSUE TITLE
Merge open-source-readiness repo into OS-Climate-Community-Hub

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/OS-Climate-Community-Hub#51]
Now that OS-Climate is an open source project, the contents of the repo https://github.com/os-climate/open-source-readiness should be merged into other existing documentation and archived.  Better to host good material in more active spaces, such as OS-Climate-Community-Hub, where it can stay up-to-date.

Assigning to @HeatherAck as principal manager of OS-Cliamte-Community-Hub.  Volunteers for OS-Climate community managers welcome!

**Comment by HeatherAck** [comment]
content moved, repo archived
