### ISSUE TITLE
Archive/delete osc-update-metadata

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/OS-Climate-Community-Hub#52]
With the new DBT/OpenMetadata pattern for managing metadata, I suspect that this repo, which was never fleshed out, is obsolete and can be deleted:

https://github.com/os-climate/osc-update-metadata

I plan to delete along with other obsolete/unused repos.

**Comment by ModeSevenIndustrialSolutions** [comment]
I have archived this repository. It's reversible, so safer. We can delete later if nobody squeals.
