### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by suppathak** [os-climate/OS-Climate-Community-Hub#55]
Requesting onboarding for github user: suppathak

Request access to github team: <team-name(s)>

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by suppathak** [comment]
cc @Shreyanand 
cc @erikerlandson

**Comment by HeatherAck** [comment]
Welcome to OS-Climate @suppathak! - it looks like you have access to os-climate and odh.  Please let me know if you need access to more teams (e.g. corp data pipeline)
