### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by Jeevi281** [os-climate/OS-Climate-Community-Hub#57]
Requesting credentials for github user: Jeevi281

Requesting credentials for the bucket: <bucket-name>

Email address to send a credential download link: jeevithapm2018@gmail.com

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

cc: @HeatherAck

**Comment by HeatherAck** [comment]
@erikerlandson can you please provide credentials to @Jeevi281 Thank you!

**Comment by erikerlandson** [comment]
I have sent a download link (and password separately)

**Comment by Jeevi281** [comment]
Received the credentials, Thanks! @erikerlandson @HeatherAck
