### ISSUE TITLE
Request for OSC physical landing S3 bucket credentials

### ISSUE THREAD

**Issue by ashuYB** [os-climate/OS-Climate-Community-Hub#58]
Helllo team,

Can you kindly send me teh OSC physical landing S3 bucket credentials for CL2 cluster please 

Thanks 
Ashu

**Comment by ashuYB** [comment]
Hi Ryan,

Thank you ... yes, the email is ***@***.***

Best
Ashu
________________________________

**Comment by rynofinn** [comment]
I see that github is filtering out email addresses.  So I'll have to find another way to deliver the credentials.  I'll do some research and reply with a plan in the next days.

**Comment by ashuYB** [comment]
thank you
________________________________

**Comment by rynofinn** [comment]
I am reluctant to add extra steps to a simple request, but as this involves sensitive credentials, we could proceed by you creating a ticket at https://support.linuxfoundation.org.  This would help ensure the safety of the credentials.
Under support, the ticket would be in the category of "Project Support Services" and then "Get IT help".
Pick the project "OS Climate" and make the request for the credentials.

I'll be able to approve and respond from there.

**Comment by ashuYB** [comment]
Thank you!  I did that.

[cid:26c8befa-0bc0-4941-a622-3ec98c40b48e]




________________________________

**Comment by rynofinn** [comment]
Hello Ashu,
This link should verify your email and then allow you to see the credentials.  Let us know if there is any difficulty with getting or using the credentials.
https://share.1password.com/s#PDrNiSZsmdUbJLf61xpbeZ-7OezGHEnZ0PurgTd9wO0
