### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by ThaanusheeB** [os-climate/OS-Climate-Community-Hub#59]
Requesting credentials for github user: ThaanusheeBalamurugan

Requesting credentials for the bucket: OSC_S3_BUCKET

Email address to send a credential download link: thaanusheebalamurugan@gmail.com

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by Thaanushee** [comment]
@erikerlandson
@HeatherAck

**Comment by HeatherAck** [comment]
@rynofinn I approve access

**Comment by ThaanusheeB** [comment]
@rynofinn

**Comment by rynofinn** [comment]
Hello, thanks for the reminder.  Here is the link that is valid just for your email address:
https://share.1password.com/s#onK-5RQmjaPVJQ4qjZNofpxztr0e66VuG5s6CDv4WVc

**Comment by HeatherAck** [comment]
closing - create new issue if still lack access.
