### ISSUE TITLE
Request credentials for an os-climate bucket for itr-data-pipeline

### ISSUE THREAD

**Issue by Dhanush-dk** [os-climate/OS-Climate-Community-Hub#64]
Requesting credentials for github user: Dhanush-dk

Requesting credentials for the bucket: s3 bucket

Email address to send a credential download link: dhanushkandasamy13@gmail.com

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by Dhanush-dk** [comment]
@rynofinn

**Comment by HeatherAck** [comment]
closing - please let us know if you still need access
