### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by Dhanush-dk** [os-climate/OS-Climate-Community-Hub#65]
Requesting onboarding for github user: Dhanush-dk

Request access to github team: <team-name(s)>

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
@Dhanush-dk I added you to ITR and ODH - please let me know if there are other projects teams, you are interested in.
