### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by maknop** [os-climate/OS-Climate-Community-Hub#67]
Requesting credentials for github user: maknop

Requesting credentials for the bucket: <bucket-name>

Email address to send a credential download link: contact@mattknop.dev

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
Hi @ryanaslett and @rynofinn - I approve access.
