### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by heshiming** [os-climate/OS-Climate-Community-Hub#69]
Requesting credentials for github user: heshiming

Requesting credentials for the bucket: s3://redhat-osc-physical-landing-647521352890/SPGI_ESG_Filings/

Email address to send a credential download link: heshiming@gmail.com

Request checklist:
- [x] User can establish connection with the bucket
- [x] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
adding Ryan and Ryan to provide access.

**Comment by ryanaslett** [comment]
You should be able to access the creditials at this URL, by logging in with your github account: https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys

Please let me know if that doesnt work.
