### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by gersh** [os-climate/OS-Climate-Community-Hub#70]
Requesting onboarding for github user: gersh

Request access to github team: corporate_data, corporate_data_pipeline

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Hi @gersh - Welcome to OS-Climate!  Please let me know if you need any support with on-boarding.

**Comment by gersh** [comment]
I can't access https://github.com/os-climate/corporate_data_pipeline.

**Comment by gersh** [comment]
Thank you.
