### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by MJAmundi** [os-climate/OS-Climate-Community-Hub#72]
Requesting onboarding for github user: <MJAmundi>

Request access to github team: <team-name(s)>

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Hi - I invited you to the org and the main set of project teams.  Please feel free to reach out to me with any questions (hackenhusen@os-climate.org).

**Comment by HeatherAck** [comment]
@MJAmundi - let us know if you need access to data (Trino/S3/open metadata)

**Comment by MJAmundi** [comment]
Hi @HeatherAck - Thanks for providing access. Indeed, I'd like to access data for the main projects, let me know the process.
