### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by ana-lam** [os-climate/OS-Climate-Community-Hub#73]
Requesting onboarding for github user: ana-lam

Request access to github team: <team-name(s)>

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Hi @ana-lam, Welcome to OS-Climate.  I invited you to our github org and various projects.  If you have any questions, please feel free to contact me at hackenhusen@os-climate.org.
