### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by squidish** [os-climate/OS-Climate-Community-Hub#75]
Requesting credentials for github user: squidish

Requesting credentials for the bucket: osc physical landing

Email address to send a credential download link: christopherfwilliams@yahoo.co.uk

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by squidish** [comment]
@HeatherAck - let me know if there's anything you need to approve this one also.

**Comment by HeatherAck** [comment]
Adding @ryanaslett to provide credentials

**Comment by ryanaslett** [comment]
You should be able to access the creditials at this URL, by logging in with your github account: https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys
