### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by mvarfima** [os-climate/OS-Climate-Community-Hub#78]
Requesting credentials for github user: mvarfima

Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Email address to send a credential download link: mvazquez@arfima.com

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
@ryanaslett - I approve access (see also: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-25206)

**Comment by mvarfima** [comment]
Thank you so much but I didn't recieve access to any s3 bucket and I am having difficulties on finding hazard datasets and physical assets allocation datasets.

Could you please guide me? I'm a bit lost. Thank you in advance.

**Comment by HeatherAck** [comment]
@ryanaslett will provide access shortly.  please check out this sample notebook for the riskthinking.ai data:  https://github.com/os-climate/data-platform-demo/blob/master/notebooks/riskthinking-tutorial.ipynb, also open metadata can provide info on asset data:  https://openmetadata-openmetadata.apps.odh-cl2.apps.os-climate.org/signin

**Comment by mvarfima** [comment]
Great, thank you, but I didn't recieve the email with the credential link. Im writing to you because I am having issues with my email provider and your email migth be lost. SO in case you sent it to me, could you please resend it ?

**Comment by HeatherAck** [comment]
@ryanaslett can you provide/resend?

**Comment by mvarfima** [comment]
I just recieved the email. Thank you so much to both.

Regards.

**Comment by mvarfima** [comment]
Hello again,

But I’m having problems with the credentials. I’m getting the next error in python:

“
ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.

PermissionError: The AWS Access Key Id you provided does not exist in our records.
”

The python code is very straight forward:

s3 = s3fs.S3FileSystem(anon=False, key=S3_LANDING_ACCESS_KEY,  secret= S3_LANDING_SECRET_KEY)
s3.ls(S3_LANDING_ENDPOINT)

Can you please help me? Thanks in advance,
Manuel

**Comment by ryanaslett** [comment]
Sorry I had some confusion on how to provide access to this.

You *should* be able to login here using your github credentials and have access to this secret in open shift (then if it ever changes, this is where you will get the updated credentials)

https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys

**Comment by mvarfima** [comment]
Hi, 

sorry for the delay but github did not notify your message to my email.

Yes, I can access that link and view the new keys but... I now have a new error: "Acess denied".

**Comment by mvarfima** [comment]
Hi,

the problem was solved after reinstalling s3fs.

Thank you so much!
