### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by mvarfima** [os-climate/OS-Climate-Community-Hub#79]
Requesting onboarding for github user: mvarfima

Request access to github team: OS-Climate-Community-Hub and hazard

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Hi - added you to the org and project teams. please let me know if you need additional on-boarding support.

**Comment by mvarfima** [comment]
That was fast! Thank so much, I'm glad to be a new member,
