### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by jtoroafs** [os-climate/OS-Climate-Community-Hub#80]
Requesting credentials for github user: jtoroafs

Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Email address to send a credential download link: jtoro@afs-server.com

Request checklist:
- [ X] User can establish connection with the bucket
- [ X] User can read files from the bucket
- [ X] User can write files to the bucket

Best regards,

**Comment by jtoroafs** [comment]
Hi @erikerlandson ,

Did you have a chance to address my resquest?

Best

**Comment by HeatherAck** [comment]
@MightyNerdEric can you please provide credentials

**Comment by ryanaslett** [comment]
@jtoroafs  wasnt a member of the odh-env-users team, so I've added them. Once they accept membership, they should be able to  access the creditials at this URL, by logging in with your github account: https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/physrisk-s3-keys

**Comment by jtoroafs** [comment]
Thansk every one.

**Comment by MightyNerdEric** [comment]
Looks like this one is complete. Closing.
