### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by jtoroafs** [os-climate/OS-Climate-Community-Hub#81]
Requesting onboarding for github user: jtoroafs

Request access to github team: OS-Climate-Community-Hub and hazard

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x ] new user invited to os-climate github org
- [ x] user invited to requested teams

Best Regards,

**Comment by HeatherAck** [comment]
Hi @jtoroafs - can you please share what parts of the platform and/or which analytical tools you are interested in?  Also what org you are from or are you an individual contributor?

**Comment by jtoroafs** [comment]
Hi @HeatherAck,

I am interested in climate data, onboarding and processing of such data, calculation of probability distributions of hazards, and the impact on physical and financial assets, as well as how to deploy a web app for data visualization. For example, how it is done in the following projects:
1) Physical Risk & Resilience
2) Transition Analysis
3) Portfolio Alignment

Currently I would be contributing by myself but my idea is involve my company as well, I still need to prestent the idea but if you could let me know what they should do to contribute as company it would be a nice step forward.

Best,

**Comment by HeatherAck** [comment]
Hi @jtoroafs - I invited you to our github and the teams above.  Given your interest in calculation of probability distribution hazards/impact on assets, I'm tagging @joemoorhouse for awareness.  The team meets weekly on Wednesdays (tech deep dive on models, etc) and Thursdays (broader discussion on project activities/planning/roadmap).  If you provide me your email, I can add you to those meetings.  Mine is hackenhusen@os-climate.org

**Comment by jtoroafs** [comment]
Many thanks. That is very helpful. 

My e-mail is:   ***@***.***> ***@***.***

Kind regards,

Juan 

Juan Toro

Tel. +34 91 125 5902

 <http://www.afs-services.com> www.afs-services.com

 

Responsable: Arfima Financial Services, S.L. / B-87038659 / C/ de Jose Bardasanos Baos 9, planta 7, 28016 Madrid /  ***@***.***> ***@***.*** / 911292874 | Finalidad principal: Gestionar la relación comercial/profesional. Atender las consultas o la información que nos solicita. | Derechos: Acceso, rectificación, supresión y portabilidad de sus datos, de limitación y oposición a su tratamiento, así como a no ser objeto de decisiones basadas únicamente en el tratamiento automatizado de sus datos, cuando procedan. | Información adicional: Puede consultar la información adicional y detallada sobre nuestra política de privacidad en  <http://afs-services.com> http://afs-services.com o escribiendo al correo electrónico  ***@***.***> ***@***.*** /  ***@***.***> ***@***.***| Confidencialidad: Si Ud. no es el destinatario y recibe este mail/fax por error, rogamos se ponga en contacto con nosotros y destruya de inmediato el mail/fax por error recibido con todos sus documentos adjuntos sin leerlos ni hacer ningún uso de los datos que en ellos figuren, ateniéndose a las consecuencias que de un uso indebido de dichos datos puedan derivarse.

**Comment by jtoroafs** [comment]
Many thanks. That is very helpful. 
My e-mail is:  jtoro@afs-service.com
Kind regards,
Juan

**Comment by HeatherAck** [comment]
great will get you added!

**Comment by HeatherAck** [comment]
the invite will come from OSC-Calendar@os-climate.org

**Comment by jtoroafs** [comment]
Hi @HeatherAck,

Do you mind send me the invitationo back, please? I have been on hollidays and I miss it. Sorry about it.

Best,

**Comment by HeatherAck** [comment]
hi @jtoroafs - just resent

**Comment by HeatherAck** [comment]
just bounced:

dd35720.kasserver.com rejected your message to the following email addresses:
[jtoro@afs-service.com (jtoro@afs-service.com)](mailto:jtoro@afs-service.com)
The email address you entered couldn't be found. Please check the recipient's email address and try to resend the message. If the problem continues, please contact your email admin.

dd35720.kasserver.com gave this error:
<jtoro@afs-service.com>: Recipient address rejected: User unknown in virtual alias table
 






Diagnostic information for administrators:
Generating server: MBX092-W9-CO-5.exch092.serverpod.net
jtoro@afs-service.com
dd35720.kasserver.com
Remote Server returned '550 5.1.1 <jtoro@afs-service.com>: Recipient address rejected: User unknown in virtual alias table'
Original message headers:
Received: from MBX092-W9-CO-1.exch092.serverpod.net (10.226.23.202) by
 MBX092-W9-CO-5.exch092.serverpod.net (10.226.23.210) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.1.2507.21; Thu, 2 Mar 2023 15:05:16 -0800
Received: from MBX092-W9-CO-1.exch092.serverpod.net ([10.226.23.202]) by
 MBX092-W9-CO-1.exch092.serverpod.net ([10.226.23.202]) with mapi id
 15.01.2507.021; Thu, 2 Mar 2023 15:05:16 -0800

**Comment by jtoroafs** [comment]
Hi Heather

There is an s missing in mail address .I tis ***@***.***

Many thanks 

Juan 

 

Juan Toro

Tel. +34 91 125 5902

 <http://www.afs-services.com> www.afs-services.com

 

Responsable: Arfima Financial Services, S.L. / B-87038659 / C/ de Jose Bardasanos Baos 9, planta 7, 28016 Madrid /  ***@***.***> ***@***.*** / 911292874 | Finalidad principal: Gestionar la relación comercial/profesional. Atender las consultas o la información que nos solicita. | Derechos: Acceso, rectificación, supresión y portabilidad de sus datos, de limitación y oposición a su tratamiento, así como a no ser objeto de decisiones basadas únicamente en el tratamiento automatizado de sus datos, cuando procedan. | Información adicional: Puede consultar la información adicional y detallada sobre nuestra política de privacidad en  <http://afs-services.com> http://afs-services.com o escribiendo al correo electrónico  ***@***.***> ***@***.*** /  ***@***.***> ***@***.***| Confidencialidad: Si Ud. no es el destinatario y recibe este mail/fax por error, rogamos se ponga en contacto con nosotros y destruya de inmediato el mail/fax por error recibido con todos sus documentos adjuntos sin leerlos ni hacer ningún uso de los datos que en ellos figuren, ateniéndose a las consecuencias que de un uso indebido de dichos datos puedan derivarse.

**Comment by jtoroafs** [comment]
Hi @HeatherAck ,

That is wired, I got the previous one on that email, jtoro@afs-services.com .

I don't know if there was any issue last night, could you try again, please?

Best,
Juan

**Comment by HeatherAck** [comment]
Hi Juan,
Just resent - no bounce back. Please let me know if you didn't receive the invites.

Have a great weekend!

**Comment by jtoroafs** [comment]
Thanks 

I received invites for Physical Risk Weekly Meeting on Wensdays

Regards,

Juan 

 

Juan Toro

Tel. +34 91 125 5902

 <http://www.afs-services.com> www.afs-services.com

 

Responsable: Arfima Financial Services, S.L. / B-87038659 / C/ de Jose Bardasanos Baos 9, planta 7, 28016 Madrid /  ***@***.***> ***@***.*** / 911292874 | Finalidad principal: Gestionar la relación comercial/profesional. Atender las consultas o la información que nos solicita. | Derechos: Acceso, rectificación, supresión y portabilidad de sus datos, de limitación y oposición a su tratamiento, así como a no ser objeto de decisiones basadas únicamente en el tratamiento automatizado de sus datos, cuando procedan. | Información adicional: Puede consultar la información adicional y detallada sobre nuestra política de privacidad en  <http://afs-services.com> http://afs-services.com o escribiendo al correo electrónico  ***@***.***> ***@***.*** /  ***@***.***> ***@***.***| Confidencialidad: Si Ud. no es el destinatario y recibe este mail/fax por error, rogamos se ponga en contacto con nosotros y destruya de inmediato el mail/fax por error recibido con todos sus documentos adjuntos sin leerlos ni hacer ningún uso de los datos que en ellos figuren, ateniéndose a las consecuencias que de un uso indebido de dichos datos puedan derivarse.

**Comment by jtoroafs** [comment]
Hi @HeatherAck,

I just realized checking the error message there is a missing 's' at the end of my email, it is;
jtoro@afs-services.com

Best,
Juan
