### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by ghazia-manifest** [os-climate/OS-Climate-Community-Hub#82]
Requesting onboarding for github user: ghazia-manifest

Request access to github team: I can't find teams using the link below

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Hi @ghazia-manifest, I granted you access to our github org as well as the data extraction, physical risk, itr, transition analysis, and pcaf teams

**Comment by HeatherAck** [comment]
please reach out if you have any questions

**Comment by ghazia-manifest** [comment]
thank you!
