### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by anotb** [os-climate/OS-Climate-Community-Hub#86]
Requesting credentials for github user: anotb

Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Email address to send a credential download link: anot.irky@gmail.com

Request checklist:
- [X] User can establish connection with the bucket
- [X] User can read files from the bucket
- [X] User can write files to the bucket

**Comment by HeatherAck** [comment]
closing - let us know if you don't have access
