### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by anotb** [os-climate/OS-Climate-Community-Hub#87]
Requesting onboarding for github user: anotb

Request access to github team: not sure what the teams are

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [ ] new user invited to os-climate github org
- [ ] user invited to requested teams

**Comment by HeatherAck** [comment]
Hi @anotb - can you please let me know what group you are part of and what specific aspect of OS-Climate that you are interested in?  We have a number of teams including physical risk, transition analysis, data commons, etc.
