### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by sabrycito** [os-climate/OS-Climate-Community-Hub#92]
Requesting credentials for github user: sabrycito

Requesting credentials for the bucket: S3 Credentials for Data Loading bucket on Hive / Iceberg

Email address to send a credential download link: sabry@u-reg.com

Request checklist:
- User can establish connection with the bucket
- User can read files from the bucket
- User can write files to the bucket

**Comment by HeatherAck** [comment]
@MightyNerdEric  - approved, please provide credentials to Sabry

**Comment by sabrycito** [comment]
Hello @MightyNerdEric ! Can you send me the credentials please ? 🙏

**Comment by HeatherAck** [comment]
@ryanaslett and @MightyNerdEric can you please prioritize for today?

**Comment by MightyNerdEric** [comment]
Could you please specify the bucket by name? It is not clear from `Data Loading bucket on Hive / Iceberg` what bucket is needed, as we do not have any bucket with that name.

**Comment by sabrycito** [comment]
Hello !osc-datacommons-s3-bucket-dev02

**Comment by MightyNerdEric** [comment]
@sabrycito You should be able to access your key and secret here: https://console-openshift-console.apps.odh-cl1.apps.os-climate.org/k8s/ns/sandbox/secrets/osc-datacommons-s3-bucket-dev02

Please let me know if you have any issues accessing the credentials.

**Comment by sabrycito** [comment]
It works! Thank you very much for your help Eric.
