### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by CarlosTardon** [os-climate/OS-Climate-Community-Hub#93]
Requesting onboarding for github user: CarlosTardon

Request access to github team: odh-env-users 

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

**Comment by HeatherAck** [comment]
Hi @CarlosTardon I added you to the org along with the data commons and physical risk teams.  If you are interested in any of the other projects, please let me know.  if you need any support, feel free to contact me at hackenhusen@os-climate.org
