### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by fanmotan** [os-climate/OS-Climate-Community-Hub#95]
Requesting credentials for github user: <fanmotan>

Requesting credentials for the bucket: <redhat-osc-physical-landing-647521352890>

Email address to send a credential download link: <fan_mo1@freddiemac.com>

Request checklist:
- [x ] User can establish connection with the bucket
- [ x] User can read files from the bucket
- [ x] User can write files to the bucket

**Comment by HeatherAck** [comment]
I approve access.

**Comment by HeatherAck** [comment]
@fanmotan please let me know if you still don't have access
