### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by HeatherAck** [os-climate/OS-Climate-Community-Hub#97]
Requesting credentials for github user: GitHub ID is rickydangc, email address: rickydangc@yahoo.com.

Requesting credentials for the bucket: Physical Risk; Zarr S3 store

Email address to send a credential download link: rickydangc@yahoo.com.

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
I approve access.

**Comment by redmikhail** [comment]
@HeatherAck we may need more information regarding this request - Physical Risk team is in bit of transition in terms of the data stores (https://github.com/os-climate/physrisk/issues/133) and currently have data in both `physrisk-hazard-indicators` and  landing buckets `redhat-osc-physical-landing-647521352890` . We probably need guidance from physrisk team on which bucket to use for the data that is relevant to what Chong and team is trying to do . Adding @joemoorhouse to help with this answers

**Comment by joemoorhouse** [comment]
Hi @HeatherAck, I updated https://github.com/os-climate/physrisk/issues/133 above. We think that use of public read-only bucket might be more appropriate/convenient for this kind of use case.
