### ISSUE TITLE
Request credentials for an os-climate bucket

### ISSUE THREAD

**Issue by rickydangc** [os-climate/OS-Climate-Community-Hub#98]
Requesting credentials for github user: rickydangc

Requesting credentials for the bucket: redhat-osc-physical-landing-647521352890

Email address to send a credential download link: rickydangc@yahoo.com

Request checklist:
- [ ] User can establish connection with the bucket
- [ ] User can read files from the bucket
- [ ] User can write files to the bucket

**Comment by HeatherAck** [comment]
duplicate
