### ISSUE TITLE
Request Onboarding to OSC Data Commons

### ISSUE THREAD

**Issue by shuangzhu-code** [os-climate/OS-Climate-Community-Hub#99]
Requesting onboarding for github user: shuangzhu-code

Request access to github team: odh-env-users, and some other teams.
The main goal is to access data on companies to be able to use the ITR tool for OS-Climate and SBTi.

View teams here: https://github.com/orgs/os-climate/teams

Onboarding resources:
- [Data Commons environment setup](https://github.com/os-climate/os_c_data_commons/blob/main/docs/setup-initial-environment.md)
- [credentials.env file](https://github.com/os-climate/os_c_data_commons/blob/main/docs/credentials.env)

Onboarding checklist:
- [x] new user invited to os-climate github org
- [x] user invited to requested teams

I work for SCOR and I would like to test out the tools. Thank you very much!

**Comment by HeatherAck** [comment]
Hi @shuangzhu-code, I granted you access.  If you need anything else, please let me know. (hackenhusen@os-climate.org)
